### ISSUE TITLE
Double click on what

### ISSUE THREAD

**Issue by inv1sible** [snooze6/FiOS#2]
First off. I am a newbie to Frida, npm and nodejs. Your tool looks promising, but I cannot get it to work. My test device is jailbroken and has frida-server installed and running. At least the following is working:

```
frida-ps -U
frida-trace -U -i "CCCryptorCreate*" Twitter
```

I am struggling with https://github.com/snooze6/FiOS#Usage... Where to double-click on? AFAIU I need to first build|compile|dist FiOS, right?? So I tried (without success):

```
jarvis:FiOS tony$ make
rm -rf src/gui/core/frida/agents.js
rm -rf src/gui/node_modules
rm -rf src/gui/app/bower_components

jarvis:FiOS tony$ make install-dependencies
cd src/gui && npm install
events.js:160░░░░░░⸩ ⠇ extract:shellwords: sill extract set-blocking@2.0.0
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:195:12)
    at PassThrough.Writable.write (_stream_writable.js:242:5)
    at PassThrough.Writable.end (_stream_writable.js:480:10)
    at ReadEntry.entry.on (/opt/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:101:20)
    at ReadEntry.emit (events.js:188:7)
    at ReadEntry.emit (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:96:13)
    at Unzip.emit (events.js:188:7)
    at Unzip.emit (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
events.js:160░░░░░░⸩ ⠦ extract:babel-messages: sill extract private@0.1.8
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:195:12)
    at PassThrough.Writable.write (_stream_writable.js:242:5)
    at PassThrough.Writable.end (_stream_writable.js:480:10)
    at ReadEntry.entry.on (/opt/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:101:20)
    at ReadEntry.emit (events.js:188:7)
    at ReadEntry.emit (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/opt/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:96:13)
    at Unzip.emit (events.js:188:7)
    at Unzip.emit (/opt/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/micromatch-51d280e6/lib/expand.js'
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/micromatch-51d280e6/lib/glob.js'
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/micromatch-51d280e6/lib/utils.js'
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/bower-4fc56af3/lib/node_modules/handlebars/dist/handlebars.amd.min.js'
npm WARN udb@1.0.0 No repository field.

npm ERR! Maximum call stack size exceeded
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/fill-range-d4d67cbd/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/fill-range-d4d67cbd/index.js'
WARN tar ENOENT: no such file or directory, open '/Users/tony/Desktop/git/FiOS/src/gui/node_modules/.staging/typescript-9a6c9f0c/lib/tsserver.js'

jarvis:FiOS tony$ make dist
mkdir -p out
./src/gui/node_modules/.bin/electron-packager src/gui FiOS --platform=win32 --arch=x64 --out out
make: ./src/gui/node_modules/.bin/electron-packager: No such file or directory
make: *** [dist] Error 1

```

ANY IDEAS??? (btw: working on macOS 10.13.3 (17D47) Darwin 17.4.0 with MacPorts)

```
npm5 @5.7.1_0 (active)
nodejs6 @6.13.0_0 (active)
```

**Comment by ShilpaRanganatha** [comment]
Hi,

I am facing the same issue. What exactly am I supposed to double click on?

**Comment by snooze6** [comment]
Hello, sorry for the delay. The plan was to make the releases inmediately after making this repo public but things never go as planned.
Now you should see the distributables available for the most common platforms: windows, linux and osx under github releases section.

**Comment by inv1sible** [comment]
Thanks @snooze6 ... the following now works for me: 

```
make install-dependencies
make run-gui
```

initially I switched to branch "releases" but this seems not to be mandatory?!

**Comment by snooze6** [comment]
It will never be mandatory although it would be recommended. At the moment it is irrelevant because both branches have the same code
